### ISSUE TITLE
Make this a tutorial on the official MNE-Python page.

### ISSUE THREAD

**Issue by wmvanvliet** [ezemikulan/blender_freesurfer#2]
When MNE-Python gains native support for reading and writing .obj files (https://github.com/mne-tools/mne-python/pull/7824), I would like to update this tutorial to use it and make it part of the official documentation. Would you be ok with this?

**Comment by ezemikulan** [comment]
Hi, sorry for the late reply, I saw the new tutorial, looks great, thanks!
